packages:
  - packages/*

catalog:
  '@astronautlabs/jsonpath': ^1.1.2
  '@biomejs/biome': 2.5.12
  '@credo-ts/anoncreds': 0.7.0
  '@credo-ts/askar': 0.7.0
  '@credo-ts/core': 0.7.0
  '@credo-ts/didcomm': 0.7.0
  '@credo-ts/didcomm-push-notifications': 0.0.2-alpha-20251223125919
  '@credo-ts/indy-vdr': 0.7.0
  '@credo-ts/openid4vc': 0.7.0
  '@credo-ts/question-answer': 0.7.0
  '@credo-ts/react-native': 0.7.0
  '@hyperledger/anoncreds-react-native': 0.4.0
  '@hyperledger/indy-vdr-react-native': 0.3.0
  '@openwallet-foundation/askar-react-native': 0.6.0
  '@types/node': ^20.19.25
  '@types/react': ^19.2.18
  rxjs: ^7.8.2
  typescript: ~5.9.3

onlyBuiltDependencies:
  - '@hyperledger/anoncreds-react-native'
  - '@hyperledger/indy-vdr-react-native'
  - '@openwallet-foundation/askar-react-native'
  - cbor-extract

overrides:
  '@isaacs/brace-expansion': 5.0.1
  ajv: 8.20.0
  body-parser: 2.3.0
  'brace-expansion@<2': 1.1.18
  decode-uri-component: 0.5.0
  defu: 6.1.7
  fast-uri: 3.1.7
  fast-xml-parser: 5.11.1
  'minimatch@<4': 3.1.5
  'minimatch@^10': 10.2.6
  path-to-regexp: 8.4.2
  'picomatch@^4': 4.0.7
  postcss: 8.5.28
  qs: 6.16.0
  'uuid@7': 11.1.1
  'uuid@13': 13.0.1
  valibot: 1.4.2
  yaml: 2.9.0
