packages:
  - 'packages/*'

catalog:
  '@biomejs/biome': 2.3.11
  '@astronautlabs/jsonpath': ^1.1.2
  "@credo-ts/anoncreds": 0.6.1
  "@credo-ts/askar": 0.6.1
  "@credo-ts/indy-vdr": 0.6.1
  "@credo-ts/core": 0.6.1
  "@credo-ts/openid4vc": 0.6.1
  "@credo-ts/question-answer": 0.6.1
  "@credo-ts/react-native": 0.6.1
  "@credo-ts/didcomm": 0.6.1
  "@hyperledger/anoncreds-react-native": 0.3.4
  "@hyperledger/indy-vdr-react-native": 0.2.3
  "@openwallet-foundation/askar-react-native": 0.4.3
  rxjs: ^7.8.2

  '@types/node': ^20.19.25
  '@types/react': 19.0.0

  rimraf: 6.1.2
  typescript: ~5.9.3