packages:
  - packages/*

catalog:
  '@types/react': ^19.2.14
  '@astronautlabs/jsonpath': ^1.1.2
  '@biomejs/biome': 2.4.15
  '@credo-ts/anoncreds': 0.7.0
  '@credo-ts/askar': 0.7.0
  '@credo-ts/core': 0.7.0
  '@credo-ts/didcomm': 0.7.0
  '@credo-ts/indy-vdr': 0.7.0
  '@credo-ts/openid4vc': 0.7.0
  '@credo-ts/question-answer': 0.7.0
  '@credo-ts/react-native': 0.7.0
  '@hyperledger/anoncreds-react-native': 0.4.0
  '@hyperledger/indy-vdr-react-native': 0.3.0
  '@openwallet-foundation/askar-react-native': 0.6.0
  '@types/node': ^20.19.25
  rxjs: ^7.8.2
  typescript: ~5.9.3

onlyBuiltDependencies:
  - '@hyperledger/anoncreds-react-native'
  - '@hyperledger/indy-vdr-react-native'
  - '@openwallet-foundation/askar-react-native'
