export * from './DidCommSdk'
export * from './providers'

// Anoncreds
import {
  AnonCredsCredentialInfo,
  AnonCredsCredentialMetadataKey,
  AnonCredsCredentialOffer,
  AnonCredsCredentialsForProofRequest,
  AnonCredsDidCommCredentialFormatService,
  AnonCredsDidCommProofFormat,
  AnonCredsDidCommProofFormatService,
  AnonCredsModule,
  AnonCredsNonRevokedInterval,
  AnonCredsPredicateType,
  AnonCredsProof,
  AnonCredsProofRequest,
  AnonCredsProofRequestRestriction,
  AnonCredsRequestedAttribute,
  AnonCredsRequestedAttributeMatch,
  AnonCredsRequestedPredicate,
  AnonCredsRequestedPredicateMatch,
  LegacyIndyDidCommCredentialFormatService,
  LegacyIndyDidCommProofFormat,
  LegacyIndyDidCommProofFormatService,
  LegacyIndyProofRequest,
} from '@credo-ts/anoncreds'
// Core
import { AskarModule } from '@credo-ts/askar'
import type { InitConfig, SaveGenericRecordOption } from '@credo-ts/core'
import {
  Agent,
  Buffer,
  CacheModule,
  ClaimFormat,
  ConsoleLogger,
  CredoError,
  DidDocument,
  DidRecord,
  DidRepository,
  DidsModule,
  DifPexCredentialsForRequest,
  GenericRecord,
  JsonTransformer,
  JwkDidCreateOptions,
  JwkDidRegistrar,
  JwkDidResolver,
  KeyDidCreateOptions,
  LogLevel,
  PeerDidCreateOptions,
  Query,
  SdJwtVcRecord,
  SingleContextStorageLruCache,
  TypedArrayEncoder,
  utils,
  W3cCredentialRecord,
  W3cJsonLdVerifiableCredential,
  WebDidResolver,
} from '@credo-ts/core'
// import type {
//   GenericRecord,
//   SaveGenericRecordOption,
// } from '@credo-ts/core/build/modules/generic-records/repository/GenericRecord'
// import {
//   GetCredentialsForRequestReturn,
//   ProofFormatDataMessagePayload,
// } from '@credo-ts/core/build/modules/proofs/protocol/ProofProtocolOptions'
import {
  DidCommAutoAcceptCredential,
  DidCommAutoAcceptProof,
  DidCommBasicMessageEventTypes,
  DidCommBasicMessageRecord,
  DidCommBasicMessageRepository,
  DidCommBasicMessageRole,
  DidCommBasicMessageStateChangedEvent,
  DidCommConnectionEventTypes,
  DidCommConnectionRecord,
  DidCommConnectionStateChangedEvent,
  DidCommConnectionsModule,
  DidCommConnectionType,
  DidCommCredentialEventTypes,
  DidCommCredentialExchangeRecord,
  DidCommCredentialPreviewAttribute,
  DidCommCredentialState,
  DidCommCredentialStateChangedEvent,
  DidCommCredentialsModule,
  DidCommCredentialV2Protocol,
  DidCommDidExchangeState,
  DidCommDifPresentationExchangeProofFormatService,
  DidCommJsonLdCredentialFormatService,
  DidCommMediationRecipientModule,
  DidCommMediatorPickupStrategy,
  DidCommMessage,
  DidCommOutOfBandRecord,
  DidCommProofEventTypes,
  DidCommProofExchangeRecord,
  DidCommProofFormatGetCredentialsForRequestReturn,
  DidCommProofFormatPayload,
  DidCommProofState,
  DidCommProofStateChangedEvent,
  DidCommProofsModule,
  DidCommProofV2Protocol,
  GetCredentialFormatDataReturn,
  JsonLdFormatDataCredentialDetail,
} from '@credo-ts/didcomm'
// Indy VDR
import {
  IndyVdrAnonCredsRegistry,
  IndyVdrIndyDidResolver,
  IndyVdrModule,
  IndyVdrPoolConfig,
  IndyVdrSovDidResolver,
} from '@credo-ts/indy-vdr'
// Q&A
import {
  QuestionAnswerEventTypes,
  QuestionAnswerRecord,
  QuestionAnswerState,
  QuestionAnswerStateChangedEvent,
} from '@credo-ts/question-answer'

// Core
export {
  LogLevel,
  ConsoleLogger,
  type InitConfig,
  type DidCommConnectionRecord,
  type DidCommOutOfBandRecord,
  type DidCommCredentialExchangeRecord,
  W3cCredentialRecord,
  type DidCommProofExchangeRecord,
  type DidCommProofState,
  type DidCommDidExchangeState,
  type DidCommCredentialState,
  type DidCommCredentialPreviewAttribute,
  type JsonLdFormatDataCredentialDetail,
  Buffer,
  type DidCommBasicMessageRole,
  type GetCredentialFormatDataReturn,
  type DidCommProofFormatPayload,
  type DidCommMessage,
  type DidCommAutoAcceptProof,
  type DidCommConnectionType,
  type DidCommProofFormatGetCredentialsForRequestReturn,
  type DidCommMediationRecipientModule,
  type DidCommMediatorPickupStrategy,
  DidsModule,
  JwkDidRegistrar,
  WebDidResolver,
  JwkDidResolver,
  type DidCommCredentialsModule,
  type DidCommAutoAcceptCredential,
  type DidCommCredentialV2Protocol,
  type DidCommJsonLdCredentialFormatService,
  type DidCommProofsModule,
  type DidCommProofV2Protocol,
  type DidCommConnectionsModule,
  Agent,
  type DidCommBasicMessageRepository,
  CredoError,
  type DidCommConnectionStateChangedEvent,
  type DidCommCredentialStateChangedEvent,
  type DidCommProofStateChangedEvent,
  type DidCommConnectionEventTypes,
  type DidCommCredentialEventTypes,
  type DidCommProofEventTypes,
  type GenericRecord,
  type SaveGenericRecordOption,
  Query,
  utils,
  TypedArrayEncoder,
  type DidCommDifPresentationExchangeProofFormatService,
  JsonTransformer,
  ClaimFormat,
  CacheModule,
  SingleContextStorageLruCache,
  DidRepository,
  DidRecord,
  W3cJsonLdVerifiableCredential,
  DifPexCredentialsForRequest,
  DidDocument,
  KeyDidCreateOptions,
  PeerDidCreateOptions,
  JwkDidCreateOptions,
  SdJwtVcRecord,
}
// Anoncreds
export {
  AnonCredsCredentialOffer,
  AnonCredsCredentialsForProofRequest,
  AnonCredsRequestedAttributeMatch,
  AnonCredsRequestedPredicateMatch,
  AnonCredsNonRevokedInterval,
  AnonCredsProofRequestRestriction,
  type AnonCredsDidCommProofFormat,
  type AnonCredsDidCommProofFormatService,
  type LegacyIndyDidCommProofFormat,
  type LegacyIndyDidCommProofFormatService,
  AnonCredsPredicateType,
  AnonCredsProof,
  AnonCredsRequestedAttribute,
  AnonCredsRequestedPredicate,
  LegacyIndyProofRequest,
  AnonCredsProofRequest,
  type AnonCredsCredentialMetadataKey,
  AnonCredsModule,
  type LegacyIndyDidCommCredentialFormatService,
  type AnonCredsDidCommCredentialFormatService,
  AnonCredsCredentialInfo,
}
// Indy Vdr
export { IndyVdrAnonCredsRegistry, IndyVdrPoolConfig, IndyVdrIndyDidResolver, IndyVdrModule, IndyVdrSovDidResolver }
// Askar
export { AskarModule }
// Q&A
export { QuestionAnswerRecord, QuestionAnswerEventTypes, QuestionAnswerStateChangedEvent, QuestionAnswerState }
//Basic message
export type { DidCommBasicMessageEventTypes, DidCommBasicMessageStateChangedEvent, DidCommBasicMessageRecord }
